# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: required
language: node_js
node_js:
  - "12"

services:
  - docker

branches:
  only:
    - master # only run CI on the master branch

before_install:
  - yarn && yarn run bootstrap

script:
  - yarn run build
  - yarn run test
  - yarn run docker:build

after_success:
  - ls -R1 coverage-report/lcov.info # list the files (for debugging)
  - cat coverage-report/lcov.info | node_modules/coveralls/bin/coveralls.js # send code-coverage data to Coveralls
